### ISSUE TITLE
Crash with NMR story book

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-plot#362]
If you try to click on

https://zakodium.github.io/react-plot/?path=/story/experimental-spectra-nmr--stack-spectra

it is super slow and it crash. I wonder if it was always like.

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 could you have a look ?

**Comment by wadjih-bencheikh18** [comment]
@targos the bug isn't fixed yet
the story still crushing

**Comment by targos** [comment]
You are right. So there's another problem than the shift.

**Comment by wadjih-bencheikh18** [comment]
issue fixed
