### ISSUE TITLE
New Type Suggestion 

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/react-plot#370]
while writing documentation,

many props can be in the three format :
number => scale
string with % => pourcentage 
number as string => in px

so maybe it's better to create new type (i don't have name suggestion let's say X )
X= number| string and use it in these props 

this will help a lot in the docs

**Comment by targos** [comment]
Agreed

**Comment by stropitek** [comment]
> Not sure about the name.

Would use the term `scalar` rather than `scale`

> Scalar: capable of being represented by a point on a scale

https://www.merriam-webster.com/dictionary/scalar
