### ISSUE TITLE
ScatterSeries legend's markershape

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/react-plot#371]
https://github.com/zakodium-oss/react-plot/blob/60d1782dd813868a4674ee29ad963842b5477817/src/components/Series/ScatterSeries.tsx#L76-L88

there is a possibilty to have many markershapes in one scatterseries so it's hard to choose one

**Comment by stropitek** [comment]
In general if the legend is complicated to generate automatically, the user should opt out of automatic legend and generate a manual legend IMO

**Comment by wadjih-bencheikh18** [comment]
yes but the problem is when it's not complicated , makershape="star" we still have a circle in the legend
![image](https://user-images.githubusercontent.com/56769876/161287115-bd4d504c-7fb6-4b18-ab95-fb25b87672e4.png)

**Comment by lpatiny** [comment]
Please use for now the style of the first point.
