### ISSUE TITLE
Limite Markers & PointLabel in FunctionSerie

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/react-plot#378]
we must add step prop
when we displayMarkers
![image](https://user-images.githubusercontent.com/56769876/161433785-70f5541b-7653-4bdb-bd54-f812fe3da57b.png)

when we displayPointLabels
![image](https://user-images.githubusercontent.com/56769876/161433812-0ffe415f-2589-4bcd-8911-2a2e3b4c1c00.png)

**Comment by lpatiny** [comment]
Please do not allow those props in function series
