### ISSUE TITLE
FunctionSeries and automatic min/max

### ISSUE THREAD

**Issue by targos** [zakodium-oss/react-plot#385]
The problem now with `FunctionSeries` after these changes is that we have to specifie max,min of vertical axis too

**Implementation detail:**
how FunctionSeries work?
it take max/ min from horizantal axis if this latter exist and draw lineSeries in [min, max] domain

to specifie max / min we need to either:
- axis max, min props
- or add another series => axis will calculate automatically max, min

=> logically we need just to specifie max /min of horizontal axis to draw it .
but the problem is When Plot is empty 
```
<Plot {...DEFAULT_PLOT_CONFIG}>
      <FunctionSeries
        getY={getY}
      />
      <Axis
        min={0}
        max={20}
        position="bottom"
      />
      <Axis position="left"/>
</Plot>
```
 => vertical axis domain is not defined => no horizantal axis

![image](https://user-images.githubusercontent.com/56769876/162342619-3fd1467d-6631-486c-8220-57c49af1a6d0.png)

_Originally posted by @wadjih-bencheikh18 in https://github.com/zakodium-oss/react-plot/issues/380#issuecomment-1092337162_

**Comment by wadjih-bencheikh18** [comment]
> The problem now with `FunctionSeries` **after these changes** is that we have to specifie max,min of vertical axis too

i specifie that these are the problems after PR changes



in the current situation, the problem is that when we use FunctionSeries with another Series (that define horizantal axis domain)
the domain will start from 0 

the domain here must be [4,8]
![image](https://user-images.githubusercontent.com/56769876/162414305-8fbdb821-0b3b-4450-8df1-8e764baeb395.png)

**Comment by wadjih-bencheikh18** [comment]
to fix this issue and also https://github.com/zakodium-oss/react-plot/issues/333
i suggest that we add series type in `PlotSeriesState` (or a boolean) so that when we calculate max/min we don't take functionSeries in consideration

**Comment by wadjih-bencheikh18** [comment]
in order to not change PlotSeriesState i added ~ in functionSeries id
