### ISSUE TITLE
dynamique Plot width and height 

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/react-plot#410]
it's very usefull to make plot dynamique and responsive
We can affect width, height in the contexe with svg dimension that can be took from the ref

**Comment by targos** [comment]
FWIW, we have an implementation already available with the [`ResponsiveChart` component](https://github.com/zakodium-oss/react-d3-utils/blob/main/src/components/ResponsiveChart.tsx).

**Comment by wadjih-bencheikh18** [comment]
what i want is to make the plot take all the parent div space width="100%"
![image](https://user-images.githubusercontent.com/56769876/168874852-a7af4774-b284-47a2-9f89-c19323ead5b5.png)

**Comment by targos** [comment]
Have you tried to use ResponsiveChart? It has width: 100%

**Comment by wadjih-bencheikh18** [comment]
Yes fixed thanks
