### ISSUE TITLE
docs: add tsdoc in the code

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-plot#415]
Currently a lot of options are not documented and their default value not known.

https://github.com/zakodium-oss/react-plot/blob/c43ce783bcafe5088d6ee7bbaf1acbfe3c4d82f2/src/hooks/useCrossHair.tsx#L14

@wadjih-bencheikh18 Could you go though the code and add the documentation like in https://github.com/mljs/spectra-processing/blob/master/src/x/xGetFromToIndex.ts#L6-L19 ?

**Comment by wadjih-bencheikh18** [comment]
I think it will be even better if we add Hooks section in storybook

**Comment by stropitek** [comment]
Is it tsdoc or jsdoc that we are supposed to use?

For example tsdoc does not have a `@default` annotation but a `@defaultValue` annotation
