### ISSUE TITLE
Ticks map using tick.position

### ISSUE THREAD

**Issue by santimirandarp** [zakodium-oss/react-plot#437]
Edit: this is just a warning in the console but may be possible to fix?

Example

      <LineSeries data={[ {x:0, y:0}, {x:0, y:1} ]} />

There should not be x:0 repeated but this would be common when having multiple possible axis combinations:

Error seems to come from [this line.](https://github.com/zakodium-oss/react-plot/blob/612a5aa6ba944638062e184dba9b4712583e1986/src/components/Axis/Ticks.tsx#L55) where the `getPositions` takes an `x` value to make the ticks (it seems so.)

Console Log
This is the text error from the console:
```
Warning: Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
Ticks@http://localhost:3000/static/js/bundle.js:34723:7
VerticalAxis@http://localhost:3000/static/js/bundle.js:34910:7
LinearAxis@http://localhost:3000/static/js/bundle.js:34522:7
Axis@http://localhost:3000/static/js/bundle.js:34113:7
```

**Comment by targos** [comment]
The stack trace shows that the error happens with `VerticalAxis`, so it seems that we should use the `y` position instead of `x`.

**Comment by santimirandarp** [comment]
I see. From some examples it seems to be always the axis for which the values are the same (may have pasted the wrong error.). Also, it seems to disappear when there is max and min in the axis.

The primary ticks scale could generate the same position when the start and end are the same value, or may be you have a different explanation ?

[This line](https://github.com/zakodium-oss/react-plot/blob/612a5aa6ba944638062e184dba9b4712583e1986/src/components/Axis/LinearAxis.tsx#L21).

**Comment by targos** [comment]
I've tried the example you posted above and there's only one tick:

![image](https://user-images.githubusercontent.com/2352663/199240480-8500cda0-976e-4842-a0e8-035d83025199.png)

**Comment by targos** [comment]
OK I see, thank you for the reproducible example. The bug is in https://github.com/zakodium-oss/react-d3-utils/blob/6bdf5d6c3983973352bc4a27c72332398cbda5f6/src/hooks/useLinearPrimaryTicks.ts#L27-L39 (we apply the new scale to old ticks from the state). Working on a fix...

**Comment by santimirandarp** [comment]
Oh, I see. It makes more sense now. You are welcome.
